//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Question
    {
        public int questionID { get; set; }
        public string questionName { get; set; }
        public System.DateTime questionDT { get; set; }
        public int categoryID { get; set; }
        public int vote { get; set; }
        public int view { get; set; }
        [NotMapped]
        public int answerCount { get; set; }
        [NotMapped]
        public string categoryName { get; set; }
        [NotMapped]
        public List<Answer> answers { get; set; }
        // for two model manipulation in a view
        [NotMapped]
        public Answer answer { get; set; }
    }
}
